<a href="https://colab.research.google.com/github/BU-Spark/ds-ciss-predictive-homlessness/blob/data-cleaning-feature/S25_Final_DatasetMerging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- With dataset 3, remove the acs(rent, income, population) data and PIT data(homeless targets).
- Merge by year and CoC Number

In [ ]:
import pandas as pd

In [ ]:
df1 = pd.read_csv('/content/corrected_stuff.csv')
df2 = pd.read_csv('/content/combined_with_year (1).csv')
df3 = pd.read_csv('/content/Final_Dataset 3.csv')

In [ ]:
df1.rename(columns = {'COCNUM' : 'CoC_Number', 'year':'Year'}, inplace = True)

In [ ]:
df2.rename(columns = {'CoC Number': 'CoC_Number'}, inplace = True)

In [ ]:
df3 = df3.drop(columns = ["Total Population", "Median Gross Rent", "Median Household Income", "Overall Homeless",
                "Overall Homeless Individuals", "Overall Homeless People in Families", "Unsheltered Homeless", "Sheltered Total Homeless",
                          "Overall_Homeless_Per_Capita", "Overall_Homeless_Individuals_Per_Capita", "Overall_Homeless_People_in_Families_Per_Capita",
                          "Unsheltered_Homeless_Per_Capita", "Sheltered_Homeless_Per_Capita", "Total Year-Round Beds (ES, TH, SH)"])

df3.head()

,Poverty_Rate,Vacancy_Rate,Renter_Household_Rate,Cost_Burdened_Rate,Unemployment_Rate,Average Temperature,CoC_Number,Year,"Beds (ES, TH, SH)"
0,8.298238,7.425172,40.858279,42.153397,7.583368,5.5,AK-500,2007,884.0
1,8.298238,7.425172,40.858279,42.153397,7.583368,0.4,AK-500,2008,899.0
2,8.298238,7.425172,40.858279,42.153397,7.583368,-0.2,AK-500,2009,877.0
3,8.298238,7.425172,40.858279,42.153397,7.583368,1.5,AK-500,2010,990.0
4,8.504627,7.073878,42.293547,42.845948,7.593841,7.0,AK-500,2011,1056.0

In [ ]:
df3.rename(columns = {'CoC Number': 'CoC_Number'}, inplace = True)
df3.head()

,Poverty_Rate,Vacancy_Rate,Renter_Household_Rate,Cost_Burdened_Rate,Unemployment_Rate,Average Temperature,CoC_Number,Year,"Beds (ES, TH, SH)"
0,8.298238,7.425172,40.858279,42.153397,7.583368,5.5,AK-500,2007,884.0
1,8.298238,7.425172,40.858279,42.153397,7.583368,0.4,AK-500,2008,899.0
2,8.298238,7.425172,40.858279,42.153397,7.583368,-0.2,AK-500,2009,877.0
3,8.298238,7.425172,40.858279,42.153397,7.583368,1.5,AK-500,2010,990.0
4,8.504627,7.073878,42.293547,42.845948,7.593841,7.0,AK-500,2011,1056.0

In [ ]:
print(df1.info())
print(df2.info())
print(df3.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6646 entries, 0 to 6645
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CoC_Number              6646 non-null   object
 1   Year                    6646 non-null   int64
 2   weighted median income  6646 non-null   float64
 3   weighted median rent    6646 non-null   float64
 4   total population        6646 non-null   float64
 5   tract count             6646 non-null   float64
dtypes: float64(4), int64(1), object(1)
memory usage: 311.7+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6516 entries, 0 to 6515
Data columns (total 8 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   CoC_Number                           6516 non-null   object
 1   CoC Name                             6516 non-null   object
 2   Overall Homeless                     6516 non-null   float64
 3   Sheltered Total Homeless             6516 non-null   float64
 4   Unsheltered Homeless                 6516 non-null   float64
 5   Overall Homeless Individuals         6516 non-null   float64
 6   Overall Homeless People in Families  6516 non-null   float64
 7   Year                                 6516 non-null   int64
dtypes: float64(5), int64(1), object(2)
memory usage: 407.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6524 entries, 0 to 6523
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Poverty_Rate           6524 non-null   float64
 1   Vacancy_Rate           6524 non-null   float64
 2   Renter_Household_Rate  6524 non-null   float64
 3   Cost_Burdened_Rate     6524 non-null   float64
 4   Unemployment_Rate      6524 non-null   float64
 5   Average Temperature    6422 non-null   float64
 6   CoC_Number             6490 non-null   object
 7   Year                   6524 non-null   int64
 8   Beds (ES, TH, SH)      6524 non-null   float64
dtypes: float64(7), int64(1), object(1)
memory usage: 458.8+ KB
None

In [ ]:
# do an outer merge with an “_merge” flag
diff = df1.merge(
    df2,
    on=['CoC_Number', 'Year'],
    how='outer',
    indicator=True
)

# all pairs only in df1 (dropped from the inner join)
dropped_from_df2 = diff[diff['_merge'] == 'left_only'][['CoC_Number','Year']]
print(f"Lost from df2 ({len(dropped_from_df2)} pairs):")
print(dropped_from_df2)

Lost from df2 (260 pairs):
     CoC_Number  Year
207      AR-503  2007
208      AR-503  2008
209      AR-503  2009
210      AR-503  2010
228      AR-504  2011
...         ...   ...
4947     NY-607  2019
5569     PA-512  2007
5570     PA-512  2008
5571     PA-512  2009
5572     PA-512  2010

[260 rows x 2 columns]

In [ ]:
pairs = list(zip(dropped_from_df2['CoC_Number'], dropped_from_df2['Year']))

In [ ]:
print(pairs)
print(len(pairs))

[('AR-503', 2007), ('AR-503', 2008), ('AR-503', 2009), ('AR-503', 2010), ('AR-504', 2011), ('AR-504', 2012), ('AR-504', 2013), ('AR-504', 2014), ('AR-504', 2015), ('AR-504', 2016), ('AR-504', 2017), ('AR-504', 2018), ('AR-504', 2019), ('CA-527', 2007), ('CA-527', 2008), ('CA-527', 2009), ('CA-527', 2010), ('CA-527', 2011), ('CA-527', 2012), ('CA-527', 2013), ('CA-527', 2014), ('CA-529', 2007), ('CA-529', 2008), ('CA-529', 2009), ('CA-529', 2010), ('CA-529', 2011), ('CA-529', 2012), ('CA-529', 2013), ('CA-529', 2014), ('CA-530', 2007), ('CA-530', 2008), ('CA-530', 2009), ('CA-530', 2010), ('CA-530', 2011), ('CA-530', 2012), ('CA-530', 2013), ('CA-530', 2014), ('CA-531', 2007), ('CA-531', 2008), ('CA-531', 2009), ('CA-531', 2010), ('CA-531', 2011), ('CA-531', 2012), ('CA-531', 2013), ('CA-531', 2014), ('CA-531', 2015), ('CA-531', 2016), ('CA-531', 2017), ('CA-531', 2018), ('GA-502', 2007), ('GA-502', 2008), ('GA-502', 2009), ('GA-502', 2010), ('GA-502', 2011), ('GA-502', 2012), ('GA-508', 2007), ('GA-508', 2008), ('GA-508', 2009), ('GA-508', 2010), ('GA-508', 2011), ('GA-508', 2012), ('MA-508', 2007), ('MA-508', 2008), ('MA-508', 2009), ('MA-508', 2010), ('MA-508', 2011), ('MA-508', 2012), ('MA-508', 2013), ('MA-508', 2014), ('MA-508', 2015), ('MA-508', 2016), ('MA-508', 2017), ('MA-508', 2018), ('MA-508', 2019), ('MA-510', 2007), ('MA-510', 2008), ('MA-510', 2009), ('MA-510', 2010), ('MA-510', 2011), ('MA-510', 2012), ('MA-510', 2013), ('MA-510', 2014), ('MA-510', 2015), ('MA-510', 2016), ('MA-510', 2017), ('MA-510', 2018), ('MA-510', 2019), ('MA-510 and MA-516 Shared Jurisdiction', 2007), ('MA-510 and MA-516 Shared Jurisdiction', 2008), ('MA-510 and MA-516 Shared Jurisdiction', 2009), ('MA-510 and MA-516 Shared Jurisdiction', 2010), ('MA-510 and MA-516 Shared Jurisdiction', 2011), ('MA-510 and MA-516 Shared Jurisdiction', 2012), ('MA-510 and MA-516 Shared Jurisdiction', 2013), ('MA-510 and MA-516 Shared Jurisdiction', 2014), ('MA-510 and MA-516 Shared Jurisdiction', 2015), ('MA-510 and MA-516 Shared Jurisdiction', 2016), ('MA-510 and MA-516 Shared Jurisdiction', 2017), ('MA-510 and MA-516 Shared Jurisdiction', 2018), ('MA-510 and MA-516 Shared Jurisdiction', 2019), ('MA-517', 2007), ('MA-517', 2008), ('MA-517', 2009), ('MA-517', 2010), ('MA-517', 2011), ('MA-517', 2012), ('MA-517', 2013), ('MA-517', 2014), ('MA-517', 2015), ('MA-517', 2016), ('MA-517', 2017), ('MA-517', 2018), ('MA-517', 2019), ('MD-500', 2007), ('MD-500', 2008), ('MD-500', 2009), ('MD-500', 2010), ('MD-500', 2011), ('MD-500', 2012), ('MD-500', 2013), ('MD-500', 2014), ('MD-500', 2015), ('MD-500', 2016), ('MD-500', 2017), ('MD-500', 2018), ('MD-500', 2019), ('MD-502', 2007), ('MD-502', 2008), ('MD-502', 2009), ('MD-502', 2010), ('MD-502', 2011), ('MD-502', 2012), ('MD-502', 2013), ('MD-502', 2014), ('MD-502', 2015), ('MD-502', 2016), ('MD-502', 2017), ('MD-502', 2018), ('MD-502', 2019), ('MD-507', 2007), ('MD-507', 2008), ('MD-507', 2009), ('MD-507', 2010), ('MD-507', 2011), ('MD-507', 2012), ('MD-507', 2013), ('MD-507', 2014), ('MD-507', 2015), ('MD-507', 2016), ('MD-507', 2017), ('MD-507', 2018), ('MD-507', 2019), ('MD-508', 2007), ('MD-508', 2008), ('MD-508', 2009), ('MD-508', 2010), ('MD-508', 2011), ('MD-508', 2012), ('MD-508', 2013), ('MD-508', 2014), ('MD-508', 2015), ('MD-508', 2016), ('MD-508', 2017), ('MD-508', 2018), ('MD-508', 2019), ('MD-509', 2007), ('MD-509', 2008), ('MD-509', 2009), ('MD-509', 2010), ('MD-509', 2011), ('MD-509', 2012), ('MD-509', 2013), ('MD-509', 2014), ('MD-509', 2015), ('MD-509', 2016), ('MD-509', 2017), ('MD-509', 2018), ('MD-509', 2019), ('MD-509', 2020), ('MD-509', 2021), ('MD-509', 2022), ('MD-509', 2023), ('MD-510', 2007), ('MD-510', 2008), ('MD-510', 2009), ('MD-510', 2010), ('MD-510', 2011), ('MD-510', 2012), ('MD-510', 2013), ('MD-510', 2014), ('MD-510', 2015), ('MD-510', 2016), ('MD-510', 2017), ('MD-510', 2018), ('MD-510', 2019), ('MD-512', 2007), ('MD-512', 2008), ('MD-512', 2009), ('MD-512', 2010), ('MD-512', 2011), ('MD-512', 2012), ('MD-512', 2013), ('MD-512', 2014), ('MD-512', 2015), ('MD-512', 2016), ('MD-512', 2017), ('MD-512', 2018), ('MD-512', 2019), ('MI-513', 2007), ('MI-513', 2008), ('MI-513', 2009), ('MI-513', 2010), ('MI-513', 2011), ('MI-513', 2012), ('MI-513', 2013), ('MI-513', 2014), ('MI-513', 2015), ('MI-513', 2016), ('MI-513', 2017), ('MI-513', 2018), ('MI-513', 2019), ('MO-604', 2007), ('MO-604', 2008), ('MO-604', 2009), ('MO-604', 2010), ('MO-604', 2011), ('MO-604', 2012), ('MO-604', 2013), ('MO-604', 2014), ('MO-604', 2015), ('MO-604', 2016), ('MO-604', 2017), ('MO-604', 2018), ('MO-604', 2019), ('MO-604', 2020), ('MO-604', 2021), ('MO-604', 2022), ('MO-604', 2023), ('NJ-512', 2016), ('NY-504', 2019), ('NY-511', 2008), ('NY-516', 2019), ('NY-522', 2007), ('NY-525', 2007), ('NY-525', 2008), ('NY-525', 2009), ('NY-525', 2010), ('NY-525', 2011), ('NY-525', 2012), ('NY-525', 2013), ('NY-525', 2014), ('NY-525', 2015), ('NY-525', 2016), ('NY-525', 2017), ('NY-525', 2018), ('NY-607', 2019), ('PA-512', 2007), ('PA-512', 2008), ('PA-512', 2009), ('PA-512', 2010)]
260

In [ ]:
Cdf12 = pd.merge(df1, df2, on=['CoC_Number', 'Year'], how = 'inner')
print(df12.head())
print(df12.info())

  CoC_Number  Year  weighted median income  weighted median rent  \
0     AK-500  2007            78328.533122           1062.638009
1     AK-500  2008            78328.533122           1062.638009
2     AK-500  2009            78328.533122           1062.638009
3     AK-500  2010            78328.533122           1062.638009
4     AK-500  2011            80808.699781           1037.436470

   total population  tract count       CoC Name  Overall Homeless  \
0          284267.0         55.0  Anchorage CoC             974.0
1          284267.0         55.0  Anchorage CoC            1023.0
2          284267.0         55.0  Anchorage CoC            1267.0
3          284267.0         55.0  Anchorage CoC            1231.0
4          287390.0         55.0  Anchorage CoC            1223.0

   Sheltered Total Homeless  Unsheltered Homeless  \
0                     842.0                 132.0
1                     921.0                 102.0
2                    1110.0                 157.0
3                    1113.0                 118.0
4                    1082.0                 141.0

   Overall Homeless Individuals  Overall Homeless People in Families
0                         696.0                                278.0
1                         695.0                                328.0
2                         821.0                                446.0
3                         740.0                                491.0
4                         794.0                                429.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6386 entries, 0 to 6385
Data columns (total 12 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   CoC_Number                           6386 non-null   object
 1   Year                                 6386 non-null   int64
 2   weighted median income               6386 non-null   float64
 3   weighted median rent                 6386 non-null   float64
 4   total population                     6386 non-null   float64
 5   tract count                          6386 non-null   float64
 6   CoC Name                             6386 non-null   object
 7   Overall Homeless                     6386 non-null   float64
 8   Sheltered Total Homeless             6386 non-null   float64
 9   Unsheltered Homeless                 6386 non-null   float64
 10  Overall Homeless Individuals         6386 non-null   float64
 11  Overall Homeless People in Families  6386 non-null   float64
dtypes: float64(9), int64(1), object(2)
memory usage: 598.8+ KB
None

In [ ]:
df_all = pd.merge(df12,df3, on= ['CoC_Number', 'Year'], how = 'left')
print(df_all.info())
df_all.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6386 entries, 0 to 6385
Data columns (total 19 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   CoC_Number                           6386 non-null   object
 1   Year                                 6386 non-null   int64
 2   weighted median income               6386 non-null   float64
 3   weighted median rent                 6386 non-null   float64
 4   total population                     6386 non-null   float64
 5   tract count                          6386 non-null   float64
 6   CoC Name                             6386 non-null   object
 7   Overall Homeless                     6386 non-null   float64
 8   Sheltered Total Homeless             6386 non-null   float64
 9   Unsheltered Homeless                 6386 non-null   float64
 10  Overall Homeless Individuals         6386 non-null   float64
 11  Overall Homeless People in Families  6386 non-null   float64
 12  Poverty_Rate                         6346 non-null   float64
 13  Vacancy_Rate                         6346 non-null   float64
 14  Renter_Household_Rate                6346 non-null   float64
 15  Cost_Burdened_Rate                   6346 non-null   float64
 16  Unemployment_Rate                    6346 non-null   float64
 17  Average Temperature                  6278 non-null   float64
 18  Beds (ES, TH, SH)                    6346 non-null   float64
dtypes: float64(16), int64(1), object(2)
memory usage: 948.1+ KB
None

,CoC_Number,Year,weighted median income,weighted median rent,total population,tract count,CoC Name,Overall Homeless,Sheltered Total Homeless,Unsheltered Homeless,Overall Homeless Individuals,Overall Homeless People in Families,Poverty_Rate,Vacancy_Rate,Renter_Household_Rate,Cost_Burdened_Rate,Unemployment_Rate,Average Temperature,"Beds (ES, TH, SH)"
0,AK-500,2007,78328.533122,1062.638009,284267.0,55.0,Anchorage CoC,974.0,842.0,132.0,696.0,278.0,8.298238,7.425172,40.858279,42.153397,7.583368,5.5,884.0
1,AK-500,2008,78328.533122,1062.638009,284267.0,55.0,Anchorage CoC,1023.0,921.0,102.0,695.0,328.0,8.298238,7.425172,40.858279,42.153397,7.583368,0.4,899.0
2,AK-500,2009,78328.533122,1062.638009,284267.0,55.0,Anchorage CoC,1267.0,1110.0,157.0,821.0,446.0,8.298238,7.425172,40.858279,42.153397,7.583368,-0.2,877.0
3,AK-500,2010,78328.533122,1062.638009,284267.0,55.0,Anchorage CoC,1231.0,1113.0,118.0,740.0,491.0,8.298238,7.425172,40.858279,42.153397,7.583368,1.5,990.0
4,AK-500,2011,80808.699781,1037.436470,287390.0,55.0,Anchorage CoC,1223.0,1082.0,141.0,794.0,429.0,8.504627,7.073878,42.293547,42.845948,7.593841,7.0,1056.0

In [ ]:
df_all.to_csv('CISS_Final_Dataset', index = False)